//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan
    {
        public string MaBenhNhan { get; set; }
        public string TenBenhNhan { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaBaoHiem { get; set; }
        public string CMND { get; set; }
    }
}
