//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<double> GiaDichVu { get; set; }
        public Nullable<int> An { get; set; }
    }
}
