//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public string MaDonThuoc { get; set; }
        public string MaPhieuKham { get; set; }
        public Nullable<double> TongChiPhi { get; set; }
    }
}
