//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlbenhvienEntities : DbContext
    {
        public qlbenhvienEntities()
            : base("name=qlbenhvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<BenhVien> BenhViens { get; set; }
        public virtual DbSet<BuonBenh> BuonBenhs { get; set; }
        public virtual DbSet<ChiTietDonThuoc> ChiTietDonThuocs { get; set; }
        public virtual DbSet<ChiTietPhieuDichVu> ChiTietPhieuDichVus { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DonThuoc> DonThuocs { get; set; }
        public virtual DbSet<DSThuoc> DSThuocs { get; set; }
        public virtual DbSet<GiuongBenh> GiuongBenhs { get; set; }
        public virtual DbSet<HoSoBenhAn> HoSoBenhAns { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LayMatKhau> LayMatKhaus { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuChuyenVien> PhieuChuyenViens { get; set; }
        public virtual DbSet<PhieuDichVu> PhieuDichVus { get; set; }
        public virtual DbSet<PhieuKhamBenh> PhieuKhamBenhs { get; set; }
        public virtual DbSet<PhieuNhapVien> PhieuNhapViens { get; set; }
        public virtual DbSet<PhieuXuatVien> PhieuXuatViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<VienPhi> VienPhis { get; set; }
    }
}
