//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKhamBenh
    {
        public string MaPhieuKham { get; set; }
        public string MaNV { get; set; }
        public string MaPhieuDichVu { get; set; }
        public string MaBenhNhan { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<double> TienKham { get; set; }
        public string TrangThai { get; set; }
        public string TrieuChung { get; set; }
        public string ChuanDoan { get; set; }
    }
}
