//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class VienPhi
    {
        public string MaVienPhi { get; set; }
        public string MaBenhNhan { get; set; }
        public Nullable<double> TienKham { get; set; }
        public Nullable<double> TienDichVu { get; set; }
        public Nullable<double> TienThuoc { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string MaPK { get; set; }
    }
}
